# Site setings
name: 'Zenit Kovačević'
description: '<span>Search</span><span> and NLP</span>'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "<h1>Welcome!</h1> My name is Zenit Kovačević. I'm a Software Engineer with a passion for Search Technologies and Clean Code. It’s nice to meet you."
favicon: 'assets/images/favicon/favicon.ico'
favicon_32: 'assets/images/favicon/favicon-16x16.ico'
favicon_64: 'assets/images/favicon/favicon-32x32.ico'
favicon_apple_touch: 'assets/images/favicon/apple-touch-icon.png'
baseurl: 
production_url: https://www.zenitk.com
url: https://www.zenitk.com
disqus: 'zenitk'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
ga_analytics: UA-167578302-1

# Contact form setings
email: zenit@zenitk.com
formspree: moqblgwa
contact_page_description: "Would you like to get in touch? Write a message here or contact me on <a href='https://www.linkedin.com/in/zenit-kova%C4%8Devi%C4%87-16754a72/' target='_blank'>LinkedIn</a>"
thankyou_page_description: "Your message has been successfully sent. I'll contact you very soon!"

# Social links
#twitter: 'justgoodthemes'
#facebook: 'username'
github: 'ZenitK'
#codepen: 'username'
#dribbble: 'username'
medium: '@zenit.kovacevic'
#instagram: 'username'
#pinterest: 'username'
linkedin: 'zenit-kovacevic'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
#  - text: Style Guide
#    url: /style-guide
  - text: Contact Me
    url: /contact
#  - text: Search
#    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  - jemoji  
  - jekyll-target-blank

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown
kramdown: 
  input: GFM
  syntax_highlighter: rouge
  
# Sass
sass:
  sass_dir: _sass
  style: compressed
