# Site setings
name: 'Search Relevance and Clean Code'
#description: 'Search Technology and Software Engineering'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there! My name is Zenit Kovačević. I'm a Software Engineer with a passion for Search Technologies and Clean Code. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://zenitk.com
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: zenitkovacevic@gmail.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
#twitter: 'justgoodthemes'
#facebook: 'username'
github: 'ZenitK'
#codepen: 'username'
#dribbble: 'username'
medium: '@zenit.kovacevic'
#instagram: 'username'
#pinterest: 'username'
linkedin: 'zenit-kovačević-16754a72'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact
#  - text: Search
#    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
